import express from 'express';
import { getUsers, createUser, updateUser, deleteUser, payFine, toggleSanksi } from '../controllers/userController.js';
const router = express.Router();
router.get('/', getUsers);
router.post('/', createUser);
router.put('/:id', updateUser);
router.delete('/:id', deleteUser);
router.post('/pay-fine', payFine);
router.put('/:id/toggle-sanksi', toggleSanksi);
export default router;
